### ISSUE TITLE
Feature Request: Automatically name md-file after headline

### ISSUE THREAD

**Issue by spinnaker1** [croqaz/clean-mark#3]
I have to download many articles with url formats like `https://www.example.com/827209`.

Is it possible to integrate a flag (`--name-headline`) to name the md output file after the headline of the article, instead of the url?

**Comment by croqaz** [comment]
Hi ! Thanks for taking the time to write this issue.
Sounds like a good idea, I can see the use-case.
I would call it `name-title` because the field is called "title".

Feel free to write the code yourseld if you want :) It should be pretty easy to do in `/bin/clean-mark`.
If not, I will to do this in the next days.

**Comment by spinnaker1** [comment]
Please you write the code, because I have no clue how to do this.

**Comment by croqaz** [comment]
Hi @spinnaker1 ! I just published version 0.8 on NPM and it should do exactly what you wanted.
The option is called `--name-title`.
Please check and close this issue if your problem is solved.

PS: I noticed that there are some problems in the core of clean-mark, with some websites... Unfortunately this is the best that this tool will do...
